INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
  VALUES ('Alex', 'Al', 33);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
  VALUES ('Roman', 'A', 3);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
  VALUES ('Max', 'Ali', 333);

INSERT INTO PRODUCTS (PRODUCT_NAME, PRICE, CATEGORY, GENDER, COLOR, SIZE, BALANCE)
  VALUES ('Cap' , 99, 'A', 'M' , 'red' , 8 , 3);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRICE, CATEGORY, GENDER, COLOR, SIZE, BALANCE)
  VALUES ('Short' , 31, 'B', 'M' , 'white' , 52 , 7);