INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
  VALUES ('Alex', 'Al', 33);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
  VALUES ('Roman', 'A', 3);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
  VALUES ('Max', 'Ali', 333);