CREATE TABLE USERS (
  ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  FIRST_NAME VARCHAR(32) NOT NULL,
  LAST_NAME VARCHAR(32) NOT NULL,
  AGE NUMBER
);

CREATE TABLE PRODUCTS (
  ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  PRODUCT_NAME VARCHAR(32) NOT NULL,
  PRICE VARCHAR(32) NOT NULL,
  CATEGORY VARCHAR(32) NOT NULL,
  GENDER VARCHAR(32) NOT NULL,
  COLOR VARCHAR(32) NOT NULL,
  SIZE VARCHAR(32) NOT NULL,
  BALANCE NUMBER
);

CREATE TABLE ORDERS (
  ORDERID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USERID NUMBER NOT NULL,
  PRODUCTID NUMBER NOT NULL,
  FOREIGN KEY (USERID) REFERENCES USERS(ID),
  FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID),
  TOTAL_PRICE VARCHAR(32) NOT NULL,
  AMOUNT NUMBER
);


